# Generated by Django 3.1.1 on 2020-09-23 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect4API', '0002_auto_20200923_1733'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playerturn',
            unique_together=set(),
        ),
    ]
